### ISSUE TITLE
JSON-Schema validation

### ISSUE THREAD

**Issue by cebe** [php-openapi/yii2-app-api#1]
- https://philsturgeon.uk/api/2018/03/30/openapi-and-json-schema-divergence/
- https://philsturgeon.uk/api/2018/04/13/openapi-and-json-schema-divergence-solved/

**Comment by cebe** [comment]
- https://philsturgeon.uk/api/2018/04/13/openapi-and-json-schema-divergence-solved/

**Comment by cebe** [comment]
fixed by #23

**Comment by cebe** [comment]
@philsturgeon, just seen that the links to your blog result in 404, looks like the redirects are broken.

**Comment by philsturgeon** [comment]
Fixed the redirects to take them to their new home on APIs You Wont Hate blog.
